### ISSUE TITLE
CTD while using villager market

### ISSUE THREAD

**Issue by aktanoorde** [faceofcat/Villager-Market#12]
Hello!
[This is all occuring in enigmatica 2. I've added a few mods, my modlist is attached.]
So, I'm receiving the same issue as previous that was closed. I am receiving consistent CTDs when using the villager market. It doesn't happen unless I do multiple trades in the window without closing it. Doesn't seem to matter if I use the single or the max trade button. Seems to be connected to trades refreshing as I'm using the market block. 

I have a platform next to a 3x3x4 pit full of villagers. The market block is next to me on my platform. There's a 3x3 of cyclic noise cancelers above the villager pit. The variety of villagers I trade with does not seem to matter. They are spawned from a "Soul Shards Respawn" soul cage. I will try to replicate this with spawn egg and/or naturally generated villagers in an actual village if you think it'll make a difference. 

I've attached a diagram explaining my setup (it's crappy mspaint, sorry), screenshots of my actual setup, my modlist, and two crashlogs. The cause of the crash is repeatedly "java.util.ConcurrentModificationException".

Let me know if you need me to get you anything else or replicate stuff for you under different conditions. I really love your mod and appreciate the effort you put into it, so I'm happy to help however I can.

![crappymspaint enigmatica 2 villager market crash](https://user-images.githubusercontent.com/47310798/64034928-94a76800-cb1d-11e9-8ce1-402ff6ee4d47.png)

![2019-08-30_11 59 41](https://user-images.githubusercontent.com/47310798/64035040-c4ef0680-cb1d-11e9-8c55-daf0916e93a9.png)
![2019-08-30_11 59 57](https://user-images.githubusercontent.com/47310798/64035041-c4ef0680-cb1d-11e9-8ad9-97dbbc6dc674.png)
![2019-08-30_11 59 31](https://user-images.githubusercontent.com/47310798/64035042-c4ef0680-cb1d-11e9-9140-92c4e0bf7c0c.png)
![2019-08-30_11 59 51](https://user-images.githubusercontent.com/47310798/64035046-c91b2400-cb1d-11e9-8a32-a9edf10e56b4.png)
![2019-08-30_12 00 05](https://user-images.githubusercontent.com/47310798/64035047-c91b2400-cb1d-11e9-95e9-fa2595db00a3.png)
![2019-08-30_11 59 37](https://user-images.githubusercontent.com/47310798/64035048-c91b2400-cb1d-11e9-991b-7da123a8ed5e.png)
![e2 modlist](https://user-images.githubusercontent.com/47310798/64035393-a76e6c80-cb1e-11e9-9f14-c49929847969.png)
[crash-2019-08-22_15.04.22-client.txt](https://github.com/MinecraftModDevelopmentMods/Villager-Market/files/3560680/crash-2019-08-22_15.04.22-client.txt)
[crash-2019-08-30_11.41.38-client.txt](https://github.com/MinecraftModDevelopmentMods/Villager-Market/files/3560681/crash-2019-08-30_11.41.38-client.txt)

**Comment by katubug** [comment]
I believe I'm having this same issue.

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.4](http://enthusiasticraft.cf/modpack-update-1-7-4/#modlist)
* **Mod versions:** villager-market-1.12.2-1.0.1

Crash log: https://paste.dimdev.org/avipevayok.mccrash

And here's an image of the screen after the crash occurred. VanillaFix tried to prevent a full CTD but it created this bizarre flickering mess:
![crash](https://user-images.githubusercontent.com/20935286/66710125-c3794680-ed37-11e9-83ed-25b440c98705.jpg)

At this point I had not done any trades whatsoever with the present villagers. I suspect that the issue was either due to there being too many villagers to render, or because one of the modded villagers in my pack was somehow incompatible?

Please let me know if I can provide any other information :) Thanks for your time!

**Comment by mhelvens** [comment]
I'm experiencing the same issue. I can't find the logs anymore, but it was a `ConcurrentModificationException` crashing Minecraft when I opened the villager market UI. I had used it succesfully before with the exact same group of villagers, but when I opened it this time, I got an empty list for a few seconds (like katubug's screenshot), then a crash.

**Comment by Pultex** [comment]
This is what I got or part of it any way

`// But it works on my machine.

Time: 1/31/20 12:57 AM
Description: Rendering screen

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.ndrei.villagermarket.VillagerMarketContainer.getRecipes(VillagerMarketContainer.java:118)
	at net.ndrei.villagermarket.VillagerMarketScreen.getRecipes(VillagerMarketScreen.java:295)
	at net.ndrei.villagermarket.VillagerMarketScreen.access$400(VillagerMarketScreen.java:24)
	at net.ndrei.villagermarket.VillagerMarketScreen$2.getSize(VillagerMarketScreen.java:153)
	at net.minecraftforge.fml.client.GuiScrollingList.drawScreen(GuiScrollingList.java:211)
	at net.ndrei.villagermarket.VillagerMarketScreen.func_146976_a(VillagerMarketScreen.java:315)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at net.ndrei.villagermarket.VillagerMarketContainer.getRecipes(VillagerMarketContainer.java:118)
	at net.ndrei.villagermarket.VillagerMarketScreen.getRecipes(VillagerMarketScreen.java:295)
	at net.ndrei.villagermarket.VillagerMarketScreen.access$400(VillagerMarketScreen.java:24)
	at net.ndrei.villagermarket.VillagerMarketScreen$2.getSize(VillagerMarketScreen.java:153)
	at net.minecraftforge.fml.client.GuiScrollingList.drawScreen(GuiScrollingList.java:211)
	at net.ndrei.villagermarket.VillagerMarketScreen.func_146976_a(VillagerMarketScreen.java:315)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
`
